apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: aceest

  template:
    metadata:
      labels:
        app: aceest

    spec:
      containers:
      - name: aceest
        image: dishaniwilp/aceest-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: APP_VERSION
          value: "v1"